#!/usr/bin/env python3
"""Assemble the published composite figures from the regenerated panels.

Figs. 3, 4, 5 and SI Figs. S5-S6 are composites: plotted panels beside crystal-structure
renderings, arranged in presentation software. This script does that arrangement in code
instead, so the whole figure is reproducible rather than only its plotted halves.

Every plotted panel comes from `Figures_R1/`, placed with `show_pdf_page`, which carries
the source PDF's vector content through unchanged - the text stays text and the lines stay
lines. Nothing is rasterized in the process.

The crystal structures come from one of two places:

  * `../../final_structure/POSCAR_*.png` - the original VESTA renders, 4130 x 1995 px.
    Placed at the sizes used here they exceed 1000 ppi. Available for CoO, CoS, CrS,
    FeAs, FeS and NiS, so Fig. 5 and SI S5-S6 use them.
  * the published PDF itself, for CuO, FeSi, VO and CrSb, which have no `.vesta` file
    and no high-resolution render anywhere in the project. Those are lifted with
    `show_pdf_page` and a clip, which reuses the embedded image object as it is - no
    resampling - but its resolution is what the published figure had: 241 ppi for the
    Fig. 3 pair, 200 ppi for the Fig. 4 pair.

Panel geometry is not guessed. Every target rectangle below was measured off the
published PDF: axes rectangles by finding the black frame in a 200 dpi render, image
rectangles from `page.get_image_info()`. The page size of each composite is the published
page size.

    python figures/compose_figures.py            # all of them -> figures/composed/
    python figures/compose_figures.py --only 3 5
"""
import argparse
import os
import re
import sys

import numpy as np
import pymupdf
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import crop_structures        # noqa: E402  - for its ink detector


def _first_dir(*candidates):
    for c in candidates:
        if c and os.path.isdir(c):
            return c
    return candidates[-1]


# The plotted panels. `figures/panels/` is the copy that ships with this repository, so a
# clone assembles the composites without anything outside it; the working tree this was
# developed in keeps the same set one level up, and $FIGURE_PANELS overrides both.
PANELS = _first_dir(os.environ.get('FIGURE_PANELS'),
                    os.path.join(HERE, 'panels'),
                    os.path.join(HERE, '..', '..', 'Figures_R1'))

# The published PDFs, which are NOT part of this repository - they sit beside the
# manuscript. Two things read them and both are optional:
#   * the H_sigma labels take their Cambria Math out of figure5.pdf; without it they are
#     set in Times New Roman Italic instead, at sizes matched to the published glyphs
#   * a crystal structure with no PNG in figures/structures/ falls back to the image
#     embedded in the published figure. All ten have a PNG, so this never fires.
PUBLISHED = _first_dir(os.environ.get('PUBLISHED_FIGURES'),
                       os.path.join(HERE, '..', '..', 'reviewer_verification'))

OUTDIR = os.environ.get('COMPOSE_OUTDIR', os.path.join(HERE, 'composed'))

# Times New Roman, for the panel letters and the Fig. 5 value blocks. Not redistributable,
# so it is looked for rather than shipped; see reference_plots/_fonts.py.
FONT_DIRS = [os.environ.get('TIMES_FONT_DIR', ''), os.path.join(HERE, 'fonts'),
             os.path.expanduser('~/.fonts'), os.path.expanduser('~/.local/share/fonts'),
             '/usr/share/fonts/truetype/msttcorefonts']


def find_font(name):
    for d in FONT_DIRS:
        if d and os.path.isfile(os.path.join(d, name)):
            return os.path.join(d, name)
    return None


TIMES = find_font('times.ttf')
TIMES_BD = find_font('timesbd.ttf')
TIMES_IT = find_font('timesi.ttf')

# Names PyMuPDF files the embedded fonts under. They must NOT be one of its reserved
# base-14 aliases - 'tiro', 'tibo', 'tiit', 'tibi' and the rest. Passing a reserved alias
# makes insert_text ignore `fontfile` and reference the base-14 Times instead, silently:
# the page still reads correctly in any viewer that has a Times, and `get_fonts()` reports
# it as `Times-Roman ... n/a`, not embedded. Journals want every font embedded.
F_ROMAN, F_BOLD, F_ITALIC, F_GREEK, F_MATH = 'tnr', 'tnrb', 'tnri', 'tnrg', 'cmma'


def page_size(path):
    """(width, height) of a panel PDF, in points.

    Read rather than written down. These panels are regenerated by code with knobs in it -
    turn up a type size and the canvas grows with it - and a constant here would not fail
    when it went stale, it would silently stretch the panel by the difference, because the
    panel is placed on a rectangle.
    """
    src = pymupdf.open(path)
    r = src[0].rect
    src.close()
    return r.width, r.height


def image_aspect(path):
    with Image.open(path) as im:
        return im.size[0] / im.size[1]


def place_pdf(page, src_path, axes_src, axes_dst):
    """Put `src_path` on `page` so its axes rectangle lands on `axes_dst`.

    Both rectangles are (x0, y0, x1, y1) in points, in their own page's coordinates.
    The scale is taken from the width; the source keeps its own aspect, so a source whose
    panel proportions already match the published one lands on it in both directions.
    """
    src = pymupdf.open(src_path)
    sp = src[0].rect
    sx0, sy0, sx1, sy1 = axes_src
    tx0, ty0, tx1, ty1 = axes_dst
    scale = (tx1 - tx0) / (sx1 - sx0)
    rect = pymupdf.Rect(tx0 - sx0 * scale, ty0 - sy0 * scale,
                        tx0 - sx0 * scale + sp.width * scale,
                        ty0 - sy0 * scale + sp.height * scale)
    page.show_pdf_page(rect, src, 0)
    src.close()
    return rect


def place_clip(page, src_path, clip, dst):
    """Copy a region of a published page onto `page`, reusing its objects unchanged."""
    src = pymupdf.open(src_path)
    page.show_pdf_page(pymupdf.Rect(*dst), src, 0, clip=pymupdf.Rect(*clip))
    src.close()


def place_image(page, img_path, dst):
    page.insert_image(pymupdf.Rect(*dst), filename=img_path, keep_proportion=True)


# Structures go in with place_ink() rather than place_image(): it lines up what is DRAWN in
# the file with the target rectangle instead of the file's own edges, so a replacement
# render with a margin of its own still lands at the same size. It is defined further down,
# beside the figures that first needed it.



def extract_image(src_path, xref, smask, out_png):
    """Pull one embedded image out of a PDF, with its transparency, as a PNG.

    `show_pdf_page` with a clip would be easier, but it carries the whole source page's
    resources into the output - clipped out of sight, yet still there. Placing Fig. 3's
    two structures that way embedded every panel of the published figure twice. Taking
    just the image keeps the composite to what it shows.
    """
    doc = pymupdf.open(src_path)
    pix = pymupdf.Pixmap(doc, xref)
    if pix.alpha:                       # a colour pixmap cannot take a second alpha
        pix = pymupdf.Pixmap(pix, 0)
    if smask:
        pix = pymupdf.Pixmap(pix, pymupdf.Pixmap(doc, smask))
    pix.save(out_png)
    doc.close()
    return out_png


def structure(name, pub_pdf, xref, smask, tmp):
    """The structure image for `name`, preferring a high-resolution render if there is one.

    Drop a file at figures/structures/<name>.png - a VESTA render at whatever resolution
    you have, transparent or white background, cropped to the structure - and it is used
    instead of the one embedded in the published PDF. Nothing else has to change: the
    composite places it on the same rectangle either way, so a sharper file simply
    raises the ppi. Without one, the published image is extracted and used as it is.
    """
    override = os.path.join(HERE, 'structures', f'{name}.png')
    if os.path.isfile(override):
        return override, True
    if not os.path.isfile(pub_pdf):
        raise SystemExit(
            f'no structure image for {name}: figures/structures/{name}.png is missing and '
            f'the published PDF it would otherwise be lifted from ({pub_pdf}) is not here. '
            f'See figures/structures/README.md.')
    return extract_image(pub_pdf, xref, smask, os.path.join(tmp, f'{name}.png')), False


def text_centre(page, s, cx, baseline, size, bold=False):
    font = pymupdf.Font(fontfile=TIMES_BD if bold else TIMES)
    w = font.text_length(s, fontsize=size)
    page.insert_text((cx - w / 2, baseline), s, fontsize=size,
                     fontname=F_BOLD if bold else F_ROMAN,
                     fontfile=TIMES_BD if bold else TIMES)


def text_centre_runs(page, runs, cx, baseline, size):
    """Centre a line made of italic and upright runs, e.g. an italic `p/d` then the rest."""
    fonts = {False: pymupdf.Font(fontfile=TIMES), True: pymupdf.Font(fontfile=TIMES_IT)}
    total = sum(fonts[it].text_length(t, fontsize=size) for t, it in runs)
    x = cx - total / 2
    for t, it in runs:
        page.insert_text((x, baseline), t, fontsize=size,
                         fontname=F_ITALIC if it else F_ROMAN,
                         fontfile=TIMES_IT if it else TIMES)
        x += fonts[it].text_length(t, fontsize=size)


def letter(page, s, x, y, size=15):
    page.insert_text((x, y), s, fontsize=size, fontname=F_BOLD,
                     fontfile=TIMES_BD, color=(0, 0, 0))


# The H_sigma that labels the two spin colorbars on Figs. 4 and 5 and SI S5-S6. All four
# published ones are the same: an italic H with an italic sigma subscript, 24.0 pt over
# 17.5 pt, set in Cambria Math.
#
# Cambria Math is a Microsoft font and is not in this repository, but the published PDFs
# embed a subset of it, and that subset is the same typeface the published label uses.
# `cambria_math()` lifts it out and hands back a usable font file; `h_sigma()` falls back
# to Times New Roman Italic when it cannot.
CAMBRIA_PT, CAMBRIA_OFF = (24.00, 17.52), (16.08, 4.93)   # as published
TIMES_HSIG_PT, TIMES_HSIG_OFF = (24.11, 19.57), (15.30, 4.85)

_cambria = ...          # None once the lift has been tried and failed


def cambria_math():
    """The published figures' own Cambria Math, extracted and made addressable.

    The embedded subset cannot be used as it is. It is a Type0 font with Identity-H
    encoding, so its glyphs are addressed by glyph id, and its `cmap` carries only the six
    code points the published pages happened to need - `H` and `sigma` are not among them,
    because the published label uses the mathematical alphanumerics U+1D43B and U+1D70E.
    U+1D43B is reachable; U+1D70E is not, and PyMuPDF draws a blank for it.

    The font's own `ToUnicode` map says which glyph is which - <072A> -> U+1D43B and
    <0C19> -> U+1D70E - and under Identity-H the code IS the glyph id. Those two glyphs are
    added to the `cmap` at `H` and `sigma`, and the result behaves like an ordinary font.

    Returns a path, or None if the published PDF or fontTools is not available.
    """
    global _cambria
    if _cambria is not ...:
        return _cambria
    _cambria = None
    try:
        from fontTools.ttLib import TTFont
        src = pymupdf.open(os.path.join(PUBLISHED, 'figure5.pdf'))
        xref = next(f[0] for f in src[0].get_fonts(full=True) if 'CambriaMath' in f[3])
        buf = src.extract_font(xref)[3]
        # ToUnicode, as <code> <utf-16be codepoint> pairs; keep the two we need
        obj = src.xref_object(xref, compressed=False)
        tu = int(re.search(r'/ToUnicode (\d+) 0 R', obj).group(1))
        cmap = src.xref_stream(tu).decode('latin-1')
        want = {'D835DC3B': 0x0048, 'D835DF0E': 0x03C3}      # 1D43B -> H, 1D70E -> sigma
        gids = {want[u.upper()]: int(c, 16)
                for c, u in re.findall(r'<([0-9A-Fa-f]{4})>\s*<([0-9A-Fa-f]{8})>', cmap)
                if u.upper() in want}
        src.close()
        if len(gids) != 2:
            return None
        tmp = os.path.join(OUTDIR, '_tmp')
        os.makedirs(tmp, exist_ok=True)
        raw = os.path.join(tmp, 'cambria_subset.ttf')
        open(raw, 'wb').write(buf)
        font = TTFont(raw)
        order = font.getGlyphOrder()
        for table in font['cmap'].tables:
            for cp, gid in gids.items():
                table.cmap[cp] = order[gid]
        out = os.path.join(tmp, 'cambria_math.ttf')
        font.save(out)
        font.close()
        _cambria = out
    except Exception as exc:
        print(f'  [note] could not use the published Cambria Math ({exc}); '
              f'H_sigma falls back to Times New Roman Italic')
    return _cambria


def h_sigma(page, x, baseline):
    """Draw H_sigma with its H's text origin at (x, baseline)."""
    font = cambria_math()
    if font is not None:
        (hp, sp), (dx, dy) = CAMBRIA_PT, CAMBRIA_OFF
        page.insert_text((x, baseline), 'H', fontsize=hp, fontname=F_MATH, fontfile=font)
        page.insert_text((x + dx, baseline + dy), '\u03c3', fontsize=sp,
                         fontname=F_MATH, fontfile=font)
        return
    # Times New Roman Italic instead. Its sizes are matched to the published glyphs' INK
    # boxes rather than to the published point sizes, because per point Times' capital is
    # larger and its sigma smaller than Cambria Math's. The sigma also needs
    # encoding=TEXT_ENCODING_GREEK - the font carries the glyph, but PyMuPDF's default
    # simple encoding cannot reach it and the character comes out blank.
    (hp, sp), (dx, dy) = TIMES_HSIG_PT, TIMES_HSIG_OFF
    page.insert_text((x, baseline), 'H', fontsize=hp, fontname=F_ITALIC, fontfile=TIMES_IT)
    page.insert_text((x + dx, baseline + dy), '\u03c3', fontsize=sp,
                     fontname=F_GREEK, fontfile=TIMES_IT,
                     encoding=pymupdf.TEXT_ENCODING_GREEK)


# ---------------------------------------------------------------------------------
# Fig. 3 - a-c column, then CuO and FeSi structures over their band panels
# ---------------------------------------------------------------------------------
def figure3(doc):
    """Fig. 3 - the a-c column beside the CuO and FeSi columns.

    Laid out from a few numbers rather than pinned to the published rectangles, because
    the panels are no longer the published sizes: a-c is enlarged, the two band panels
    are taller, and the gutter between the two halves is a tenth of what it was. The page
    grows with them; its width is the published 778.1 pt and its height follows the a-c
    column.
    """
    PAGE_W = 778.1
    AC_SCALE = 1.05          # of the a-c source page; it sets the page height
    GUTTER = 5.4             # a tenth of the 54.2 pt the published layout leaves here
    D_AX = (55.2, 13.7, 266.3, 468.0)     # axes rectangle inside each source page
    E_AX = (31.2, 13.7, 231.0, 468.0)
    TEXT_BASELINES = (36.7, 55.9, 75.1)   # as published
    TEXT_SIZE = 16
    LETTER_PT = 20                        # every panel letter, every figure

    # Every source page size is read rather than written down; see page_size().
    src = pymupdf.open(f'{PANELS}/Fig3(a-c).pdf')
    AC = (src[0].rect.width, src[0].rect.height)
    D = page_size(f'{PANELS}/Fig3(d).pdf')
    E = page_size(f'{PANELS}/Fig3(e).pdf')

    page_h = AC[1] * AC_SCALE
    page = doc.new_page(width=PAGE_W, height=page_h)
    pub = f'{PUBLISHED}/figure3.pdf'

    # --- a-c, left, filling the page height -------------------------------------
    page.show_pdf_page(pymupdf.Rect(0, 0, AC[0] * AC_SCALE, page_h), src, 0)
    src.close()

    # --- the two band panels share one scale, set by the width left over ---------
    x_start = AC[0] * AC_SCALE + GUTTER
    s_de = (PAGE_W - x_start) / (D[0] + E[0])
    band_h = D[1] * s_de
    band_top = page_h - band_h
    for path, size, ax, x0 in ((f'{PANELS}/Fig3(d).pdf', D, D_AX, x_start),
                               (f'{PANELS}/Fig3(e).pdf', E, E_AX,
                                x_start + D[0] * s_de)):
        s = pymupdf.open(path)
        page.show_pdf_page(pymupdf.Rect(x0, band_top, x0 + size[0] * s_de,
                                        band_top + size[1] * s_de), s, 0)
        s.close()

    # --- structures and their value lines, centred over each band panel ----------
    tmp = os.path.join(OUTDIR, '_tmp')
    os.makedirs(tmp, exist_ok=True)
    cols = ((25, 26, (129.4, 186.9), x_start, D, D_AX,
             ('CuO', 'MSBI: 1.018', 'SSE: 1.634 eV')),
            (27, 28, (137.2, 177.9), x_start + D[0] * s_de, E, E_AX,
             ('FeSi', 'MSBI: 0.0003', 'SSE: 0.003 eV')))
    for xref, smask, (iw, ih), x0, size, ax, lines in cols:
        cx = x0 + (ax[0] + ax[2]) / 2 * s_de
        # centred in the band between the value lines and the top of the band panel
        top = TEXT_BASELINES[-1] + 12
        iy = top + ((band_top - top) - ih) / 2
        png, hi = structure(lines[0], pub, xref, smask, tmp)
        if hi:
            print(f'  using figures/structures/{lines[0]}.png')
        place_ink(page, png, (cx - iw / 2, iy, cx + iw / 2, iy + ih))
        for s_, base in zip(lines, TEXT_BASELINES):
            text_centre(page, s_, cx, base, TEXT_SIZE)
        # baseline 24.7, not 22.5: matplotlib and PyMuPDF measure a text box
        # differently, and this is what puts the glyph tops level with panel a's
        letter(page, '(d)' if xref == 25 else '(e)',
               x0 + ax[0] * s_de - 38, 24.7, size=LETTER_PT)
    return 'Fig3'


# ---------------------------------------------------------------------------------
# Fig. 4 - a and b stacked at the left; VO and CrSb structures over one shared fatband
# ---------------------------------------------------------------------------------
def figure4(doc):
    """The right half is one figure, not two: the published panel c/d fatband is a
    single image spanning both columns, with the two spin colorbars and the H_sigma
    label at its right edge. Only the structures and the value lines above them are
    per-column, so those are placed on fractions of that image's span, taken from the
    published layout.
    """
    PAGE_W = 1147.8
    GUTTER = 6.0
    LEFT_SCALE = 1.0
    A = page_size(f'{PANELS}/Fig4(a).pdf')     # read, not written down; see page_size()
    B = page_size(f'{PANELS}/Fig4(b).pdf')
    A_AX = (74.6, 36.0, 356.0, 259.4)  # axes rectangle inside each
    B_AX = (64.8, 13.7, 342.8, 292.3)
    LETTER_PT = 20
    LETTER_BASE = 23.4   # levels every letter's glyph top with panel a's
    LETTER_LEFT = 7.1    # and its left edge; matplotlib anchors the text box,
                         # PyMuPDF the glyph, so the two differ by the bearing

    TEXT_BASELINES = (44.4, 68.4, 92.4)
    TEXT_SIZE = 20
    # fractions of the fatband's width, measured off the published page
    CX = (0.242, 0.637)                # structure / text column centres
    LETTER_X = (0.008, 0.446)          # (c) and (d)
    HSIG_X = 0.862

    page_h = (A[1] + B[1]) * LEFT_SCALE
    page = doc.new_page(width=PAGE_W, height=page_h)
    pub = f'{PUBLISHED}/figure4.pdf'

    # --- a over b, left, with their axes frames the same width and left-aligned ---
    # a's frame is 281.4 pt across and b's 278.0, so b is scaled up by the ratio and both
    # are shifted so their frames start at the same x. b's type is set at that same ratio
    # of a's sizes (see reference_plots/plot_fig4b.py), so the scaling lands the two
    # panels on the same point sizes rather than pulling them apart.
    s_a = LEFT_SCALE
    s_b = LEFT_SCALE * (A_AX[2] - A_AX[0]) / (B_AX[2] - B_AX[0])
    x_frame = A_AX[0] * s_a
    for path, size, ax, s_, y0 in (
            (f'{PANELS}/Fig4(a).pdf', A, A_AX, s_a, 0.0),
            (f'{PANELS}/Fig4(b).pdf', B, B_AX, s_b, A[1] * LEFT_SCALE)):
        x0 = x_frame - ax[0] * s_
        src = pymupdf.open(path)
        page.show_pdf_page(pymupdf.Rect(x0, y0, x0 + size[0] * s_,
                                        y0 + size[1] * s_), src, 0)
        src.close()

    # --- the shared fatband, filling the width that is left ----------------------
    x_start = max(A[0] * s_a, x_frame - B_AX[0] * s_b + B[0] * s_b) + GUTTER
    fat_w = PAGE_W - x_start
    fat_h = fat_w / image_aspect(f'{PANELS}/Fig4(c-d).png')
    fat_top = page_h - fat_h
    place_image(page, f'{PANELS}/Fig4(c-d).png',
                (x_start, fat_top, PAGE_W, page_h))

    # --- structures and value lines over their halves of it ----------------------
    tmp = os.path.join(OUTDIR, '_tmp')
    os.makedirs(tmp, exist_ok=True)
    struct = ((14, 15, (168.0, 206.8), ('VO', 'p/d electron ratio: 1', 'SSE: 0.165 eV')),
              (16, 17, (209.0, 211.2), ('CrSb', 'p/d electron ratio: 0.6',
                                        'SSE: 1.194 eV')))
    room = fat_top - (TEXT_BASELINES[-1] + 10)
    s_img = min(1.0, (room - 8) / max(h for _, _, (_, h), _ in struct))
    for (xref, smask, (iw, ih), lines), cxf, lxf in zip(struct, CX, LETTER_X):
        cx = x_start + cxf * fat_w
        w, h = iw * s_img, ih * s_img
        iy = TEXT_BASELINES[-1] + 10 + (room - h) / 2
        png, hi = structure('VO' if xref == 14 else 'CrSb', pub, xref, smask, tmp)
        if hi:
            print(f'  using figures/structures/{"VO" if xref == 14 else "CrSb"}.png')
        place_ink(page, png, (cx - w / 2, iy, cx + w / 2, iy + h))
        for s_, base in zip(lines, TEXT_BASELINES):
            text_centre(page, s_, cx, base, TEXT_SIZE)
        letter(page, '(c)' if xref == 14 else '(d)',
               x_start + lxf * fat_w, LETTER_BASE, size=LETTER_PT)

    h_sigma(page, x_start + HSIG_X * fat_w, fat_top - 10.7)

    # (a) is already drawn by its own panel; only (b) is added here, at the far left so
    # it clears that panel's topmost y tick label. It sits a little higher than the
    # a/c/d rule would put it - panel b's own top margin is thin, and LETTER_BASE would
    # leave the letter almost touching the frame - but not so high that it runs into
    # panel a's abscissa label above it
    letter(page, '(b)', LETTER_LEFT, A[1] * LEFT_SCALE + LETTER_BASE - 7.3,
           size=LETTER_PT)
    return 'Fig4'


# ---------------------------------------------------------------------------------
# Fig. 5, SI S5 and SI S6 - two structures with their descriptor values over one
# shared two-panel fatband. One layout, three sets of numbers.
# ---------------------------------------------------------------------------------
# Everything below was measured off the published pages, which agree with each other to
# well under a point: text origins from the PDF text layer, image rectangles from
# page.get_image_info(), the H_sigma origin from its ink box, and each structure's
# rectangle from where its ink actually starts and stops inside that image.
PAIR_BASELINES = (25.5, 49.5, 73.5, 97.5, 121.5)
PAIR_TEXT_PT = 20
PAIR_CX = (156.2, 409.4)          # the two column centres
PAIR_LETTERS = ((7.2, 22.9), (277.7, 22.9))
PAIR_LETTER_PT = 20
PAIR_HSIG = (528.10, 456.36)      # the published text origin of the H

PAIRS = {
    'Fig5': dict(
        page=(614.9, 796.9),
        band=('Fig5(a-b).png', (2.6, 465.2, 614.9, 796.8)),
        cols=(dict(name='FeS', ink=(54.36, 146.10, 253.08, 439.14), ratio='0.571',
                   values=('FeS', 'SSE: 1.297 eV', 'MSBI: 0.871', 'MPF: 0.533')),
              dict(name='NiS', ink=(293.70, 162.70, 519.78, 423.34), ratio='0.444',
                   values=('NiS', 'SSE: 0.823 eV', 'MSBI: 0.681', 'MPF: 0.333')))),
    'SI_5': dict(
        page=(614.3, 796.9),
        band=('SI5(a-b).png', (2.0, 465.2, 614.3, 796.8)),
        cols=(dict(name='CoO', ink=(55.44, 150.46, 252.96, 438.46), ratio='0.500',
                   values=('CoO', 'SSE: 0.972 eV', 'MSBI: 0.812', 'MPF: 0.521')),
              dict(name='CrS', ink=(310.08, 152.62, 516.24, 445.42), ratio='0.800',
                   values=('CrS', 'SSE: 0.552 eV', 'MSBI: 0.694', 'MPF: 0.517')))),
    'SI_6': dict(
        page=(616.0, 798.0),
        band=('SI6(a-b).png', (1.8, 464.2, 615.9, 798.0)),
        cols=(dict(name='CoS', ink=(42.60, 156.94, 268.68, 416.86), ratio='0.500',
                   values=('CoS', 'SSE: 1.103 eV', 'MSBI: 0.689', 'MPF: 0.333')),
              dict(name='FeAs', ink=(289.00, 157.72, 522.76, 416.68), ratio='0.429',
                   values=('FeAs', 'SSE: 1.089 eV', 'MSBI: 0.690', 'MPF: 0.333')))),
}


def ink_box(png):
    """(x0, y0, x1, y1, W, H) of the drawn part of an image, in its own pixels."""
    with Image.open(png) as im:
        if im.mode in ('RGBA', 'LA', 'P'):
            im = im.convert('RGBA')
            flat = Image.new('RGB', im.size, 'white')
            flat.paste(im, mask=im.getchannel('A'))
        else:
            flat = im.convert('RGB')
        a = np.asarray(flat).astype(int)
    m = crop_structures.ink(a)
    r = np.where(m.any(1))[0]
    c = np.where(m.any(0))[0]
    return c[0], r[0], c[-1] + 1, r[-1] + 1, a.shape[1], a.shape[0]


def place_ink(page, png, ink_rect):
    """Place `png` so its drawn part lands centred on `ink_rect`, as large as it fits.

    The published structure images carry a margin of their own, and a fresh crop carries a
    different one, so lining the FILES up would put the two structures at different sizes.
    Lining up what is drawn inside them does not: the target rectangles are the ink boxes
    measured off the published pages, and whatever margin the replacement file has simply
    hangs outside them, empty.
    """
    x0, y0, x1, y1 = ink_box(png)[:4]
    W, H = ink_box(png)[4:]
    tx0, ty0, tx1, ty1 = ink_rect
    s = min((tx1 - tx0) / (x1 - x0), (ty1 - ty0) / (y1 - y0))
    cx, cy = (tx0 + tx1) / 2, (ty0 + ty1) / 2
    ox, oy = cx - (x0 + x1) / 2 * s, cy - (y0 + y1) / 2 * s
    page.insert_image(pymupdf.Rect(ox, oy, ox + W * s, oy + H * s),
                      filename=png, keep_proportion=True)


def pair_figure(doc, key):
    spec = PAIRS[key]
    page = doc.new_page(width=spec['page'][0], height=spec['page'][1])

    # --- the two-panel fatband across the bottom, at the published rectangle -----
    # The published rectangle fixes where the band sits and how wide it is; its height
    # follows the panel's own aspect, so a regenerated panel that crops a little
    # differently still fills the width and keeps its proportions rather than being
    # squashed into last time's rectangle.
    band, band_rect = spec['band']
    x0, _, x1, y1 = band_rect
    place_image(page, f'{PANELS}/{band}',
                (x0, y1 - (x1 - x0) / image_aspect(f'{PANELS}/{band}'), x1, y1))
    h_sigma(page, *PAIR_HSIG)

    for col, cx, (lx, ly), tag in zip(spec['cols'], PAIR_CX, PAIR_LETTERS, '(a) (b)'.split()):
        # The structure keeps its own aspect and is centred in the published rectangle,
        # so a re-crop that is a few per cent taller or wider than the published image
        # stays inside the space the layout gives it.
        png = os.path.join(HERE, 'structures', f"{col['name']}.png")
        print(f"  using figures/structures/{col['name']}.png")
        place_ink(page, png, col['ink'])

        for line, base in zip(col['values'], PAIR_BASELINES):
            text_centre(page, line, cx, base, PAIR_TEXT_PT)
        # only `p/d` is italic on the last line, as published
        text_centre_runs(page, (('p/d', True), (f" electron ratio: {col['ratio']}", False)),
                         cx, PAIR_BASELINES[4], PAIR_TEXT_PT)
        letter(page, tag, lx, ly, size=PAIR_LETTER_PT)
    return key


BUILDERS = {'3': figure3, '4': figure4,
            '5': lambda doc: pair_figure(doc, 'Fig5'),
            'S5': lambda doc: pair_figure(doc, 'SI_5'),
            'S6': lambda doc: pair_figure(doc, 'SI_6')}


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--only', nargs='*', metavar='N')
    a = ap.parse_args()
    if TIMES_BD is None:
        print('[note] Times New Roman not found; panel letters fall back to a base font')
    os.makedirs(OUTDIR, exist_ok=True)
    keys = a.only or list(BUILDERS)
    for k in keys:
        if k not in BUILDERS:
            sys.exit(f'unknown figure {k!r}; choose from {sorted(BUILDERS)}')
        doc = pymupdf.open()
        stem = BUILDERS[k](doc)
        p = os.path.join(OUTDIR, f'{stem}.pdf')
        doc.save(p, garbage=4, deflate=True)
        doc.close()
        print(f'  written: {p}   ({os.path.getsize(p) / 1e6:.2f} MB)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
